# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usege', models.CharField(choices=[('Investment', 'Investment'), ('Battle', 'Battle')], max_length=20)),
                ('card_name', models.CharField(max_length=100)),
                ('card_set', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('current', models.FloatField()),
                ('profit', models.FloatField()),
                ('percent', models.FloatField()),
                ('daily', models.FloatField()),
                ('weekly', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
