# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-14 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20171103_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_set', models.CharField(max_length=10)),
                ('rarity', models.CharField(max_length=10)),
                ('user', models.CharField(default='', max_length=50)),
                ('card_link', models.CharField(default='', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('card_price', models.CharField(max_length=10)),
                ('post_date', models.CharField(max_length=10)),
                ('user', models.CharField(default='', max_length=50)),
                ('decks', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
