# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_cardhistroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcollect',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cardhistroy',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
