# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20170626_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcollect',
            name='card_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cardcollect',
            name='current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cardcollect',
            name='daily',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cardcollect',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cardcollect',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cardcollect',
            name='weekly',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cardhistroy',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
