# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-14 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20171114_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprice',
            name='card_id',
            field=models.IntegerField(default=0),
        ),
    ]
