# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-14 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_remove_cardprice_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprice',
            name='card_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
