# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lg_id', models.CharField(max_length=10)),
                ('opp_deck', models.CharField(max_length=50)),
                ('during', models.IntegerField()),
                ('game_result', models.CharField(choices=[('Win', 'Win'), ('Lose', 'Lose')], max_length=10)),
                ('user', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_format', models.CharField(choices=[('Standard', 'Standard'), ('Modern', 'Modern'), ('Pauper', 'Pauper'), ('Legacy', 'Legacy'), ('Commander', 'Commander')], max_length=20)),
                ('league_type', models.CharField(choices=[('Friendly', 'Friendly'), ('Competitive', 'Competitive')], max_length=20)),
                ('deck', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('profit', models.FloatField(default=0.0)),
                ('finish', models.BooleanField(default=False)),
                ('result', models.CharField(default='', max_length=10)),
                ('during123', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
