# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_auto_20170619_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructleague',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructleague',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
